sonar.projectKey=Aira
sonar.projectName=Aira
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_c412838902affb508e0c45f8bcf04f027d53a63a

# Sources
sonar.sources=frontend/src,backend/api,backend/voice_agent

# Tests
sonar.tests=tests

# Exclusions
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/.next/**

# Python coverage
sonar.python.coverage.reportPaths=tests/coverage.xml

# JS/TS coverage
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
