sonar.projectKey=aira
sonar.projectName=aira
sonar.projectVersion=1.0
sonar.host.url=https://sonarqube.randomw.dev
sonar.token=sqp_150fcc110f1b27a44bb5b1a859b45959c04cf652

# Sources
sonar.sources=frontend/src,backend/api,backend/voice_agent

# Tests
sonar.tests=tests

# Exclusions
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/.next/**

# Python coverage
sonar.python.coverage.reportPaths=tests/coverage.xml

# JS/TS coverage
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
